# Informations générales
site_name: Mulot NSI
site_url: https://www.mulot-nsi.fr
site_author: Yannick Mulot

# Arborescence de navigation
nav:
  - Accueil: index.md
  - SNT:
      - snt/index.md
      - Tutoriels:
          - Windows: snt/tutoriels/windows.md
          - Saisie de texte: snt/tutoriels/saisie-de-texte.md
          - ENT: snt/tutoriels/ent.md
      - Chapitre 1 - Internet:
          - snt/01-internet/index.md
          - TP1 - Naissance d'Internet: snt/01-internet/tp1-naissance-internet.md
          - TP2 - Simulation d'un réseau: snt/01-internet/tp2-simulation-reseau.md
      - Chapitre 2 - Le Web:
          - TP1 - Langage HTML: snt/02-web/tp1-langage-html.md
          - TP2 - Langage CSS: snt/02-web/tp2-langage-css.md
          - Projet - Mini-site web: snt/02-web/prj-minisite.md
  - NSI 1RE:
      - nsi1re/index.md
      - Chapitre 1 - Langages du Web:
          - TP1 - Création d'une page web: nsi1re/01-langages-web/tp1-creation-page-web.md
          - Projet - Présentez-vous: nsi1re/01-langages-web/prj-presentez-vous.md
      - Chapitre 2 - Architecture des ordinateurs:
          - TP1 - Interpréteur de commandes: nsi1re/02-ordinateurs/tp1-cli.md
      - Chapitre 3 - Bases de la programmation:
          - TP1 - Mode interactif: nsi1re/03-bases-programmation/tp1-python-mode-interactif.md
          - TP2 - Mode script: nsi1re/03-bases-programmation/tp2-python-mode-script.md
          - TP3 - Module Turtle: nsi1re/03-bases-programmation/tp3-turtle.md
      - Chapitre 4 - Les fonctions:
          - TP1 - Décomposition : nsi1re/04-fonctions/tp1-decompostion-en-sous-problemes.md
          - TP2 - Programmation défensive : nsi1re/04-fonctions/tp2-programmation-defensive.md
          - Projet - Paysage généré: nsi1re/04-fonctions/prj-paysage.md
          - Remédiation : nsi1re/04-fonctions/remediation.md

# Configuration du thème
theme:
  name: material
  language: fr
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    # - navigation.instant
  font:
    text: Roboto
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - minify:
      minify_html: true
  - search

# Extensions Markdown
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map:
        shift: Maj
        control: Ctrl
        option: Opti
        up: Haut
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - assets/js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - assets/css/style.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css