# Informations générales
site_name: Mulot NSI
site_url: https://www.mulot-nsi.fr
site_author: Yannick Mulot

# Arborescence de navigation
nav:
  - Accueil: index.md
  - SNT:
      - snt/index.md
      - Chapitre 1 - Internet:
          - snt/01-internet/index.md
          - TP1 - Naissance d'Internet: snt/01-internet/tp1-naissance-internet.md
  - NSI 1RE:
      - nsi1re/index.md
      - Chapitre 1 - Langages du Web:
          - TP1 - Création d'une page web: nsi1re/01-langages-web/tp1-creation-page-web.md
          - Projet - Présentez-vous: nsi1re/01-langages-web/prj-presentez-vous.md
      - Chapitre 2 - Les ordinateurs:
          - TP1 - Interpréteur de commandes: nsi1re/02-ordinateurs/tp1-cli.md

# Configuration du thème
theme:
  name: material
  language: fr
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    # - navigation.sections
    - navigation.tabs
    # - navigation.instant
  font:
    text: Roboto
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - minify:
      minify_html: true
  - search

# Extensions Markdown
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true